### ISSUE TITLE
load_hook doesn't seem to distinguish between "load" and "unload" with Sticky modules

### ISSUE THREAD

**Issue by DirkdeDraak** [TACC/Lmod#102]
When creating the load_hook the example shows a way to make sure the logging only occurs on "load":
```
   if (mode() ~= "load") then
      return
   end
```

I have a sticky module for our PRODUCTION environment.

Though when diplaying the mode() output it always shows "load", even when doing a "module unload" or "module purge". Though nothing when doing "module --force purge".

1st example (start with no modules loaded)
```
$ module load PRODenv/1.0 (This is a Sticky module)`
```
=> load_hook executed with "load" mode == [OK]
```
$ module unload PRODenv/1.0
```
=> load_hook executed with "load" mode == [NOT OK]

2nd example  (start with no modules loaded):
```
$ module load PRODenv/1.0 (This is a Sticky module)`
```
=> load_hook executed with "load" mode == [OK]
```
$ module load myapp/3.3
```
=> load_hook executed with "load" mode == [OK]

```
$ module purge
```
=> load_hook not called for myapp/3.3, though is called with mode "load" for PRODenv/1.0

I guess in reality Lmod performs both the unload() function and then the load() function for the sticky module, but does not do anything.

**Comment by rtmclay** [comment]
This is by design and your assumption is correct.  The way that sticky modules are implemented is that when an unload is requested it detects that the module is sticky and that module is added to a list of modules to be reloaded.  So for a sticky module:

      $ module unload PRODenv/1.0

Really means:

    $ module unload PRODenv/1.0; module load PRODenv/1.0

This is why an unload of a sticky module forces a load_hook call

Lmod does it this way because someone might make a module sticky that is in the hierarchy.  a module purge unloads all modules and then it tries to reload any sticky modules.  It might not be possible because one of the hierarchical modules might not be visible.

**Comment by DirkdeDraak** [comment]
Thank you for the explanation Robert.

/Fokko
