### ISSUE TITLE
Autocompletion in ZSH incorrectly add '.lua' to module names

### ISSUE THREAD

**Issue by dmitry-kabanov** [TACC/Lmod#200]
This behavior is observed in Lmod 6.6 and 7.0.

Autocompletion in ZSH completes module names by adding suffix '.lua':

    % module load g
    gcc/4.9.2.lua  gcc/6.2.0.lua  git/2.10.lua 

which leads to an error

    % module load gcc/6.2.0.lua
    Lmod has detected the following error:  The following module(s) are
    unknown: "gcc/6.2.0.lua"

So, I have to manually delete '.lua' after using autocompletion.

**Comment by rtmclay** [comment]
I am wondering what version of zsh shell are you using and on what O.S. you are running on.   Did you do anything special to install the lmod completion files for zsh?

Thanks,

**Comment by dmitry-kabanov** [comment]
I'm running on Ubuntu 16.04.
```
% zsh --version
zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

I simply source Lmod's `init/profile` in my ~/.zshrc.

**Comment by rtmclay** [comment]
Thanks for the bug report!

One point is that bash tab completion is completely different from zsh so sourcing the bash tab completion files usually doesn't work.  I figured out that the problem you ran into was that zsh was finding the Tmod tab completion files and not the one shipped with lmod.  Then I found out that the _ml and _module zsh files were not being installed.   The problem was that I used a bash feature that wasn't in sh in my Makefile.

Anyway the _ml and _module file are now being installed and they now work for me.  Yes zsh tab completion hasn't worked for me for a while but now they do and yes I mainly use zsh as my shell.

Please test Lmod 7.1.2 to see if it works for you.  You should log out and log back in to make sure that zsh finds the new tab completion functions.

Thanks again

**Comment by dmitry-kabanov** [comment]
Thank you, Robert.

I've installed Lmod 7.1.2 (twice actually) and made autocompletion work as described below.

1. Funny thing is that I've found a bug with zsh (probably) misconfigured. I've started to use a plugin framework for zsh `zplug` recently. It sets environment variable $ZSH that affects Lmod's `configure` script and makes `ZSH_SITE_FUNCTIONS_DIRS` empty, therefore, completion functions are not installed. This was the first try to install Lmod 7.1.2. I used the following command:

    ./configure --prefix=/home/kabanod/apps
    
2. I've tried to install it again by making $ZSH env. variable empty:

    ZSH= ./configure --prefix=/home/kabanod/apps

Now `ZSH_SITE_FUNCTIONS_DIRS` is made non-empty by the `configure` script. However, as the value is `/usr/local/share/zsh/site-functions` and it's not writable, completion functions are not installed (I make an installation without administrative permissions). I see in the commit https://github.com/TACC/Lmod/commit/dcb409dcba120303ea2757541aea0fee6aa8a75a#diff-7e056ddc530791272d363e50c1f25647 that copying of the completion functions silence the errors.
So, I've made the directory writable temporarily and reinstalled. After restarting the computer, I have `module` command autocompletion working properly:

    % module load g
    gcc        gcc/4.9.2  gcc/6.2.0  git        git/2.10 

However, `ml` command autocompletion doesn't work :( Both `_ml` and `_module` has readable-for-everyone permission.

**Comment by rtmclay** [comment]
My only suggestion is delete ~/.zcompdump then log out and back in and see if that fixes the problem.

**Comment by dmitry-kabanov** [comment]
I did as you suggested. It didn't help (still no autocompletion for `ml`).
Anyway, the `module` command has autocompletion now.

Thank you!

**Comment by rtmclay** [comment]
You are welcome.  I'm going to close this issue.  If you get any new insight please let me know.
