### ISSUE TITLE
zsh tab completion with .lua files

### ISSUE THREAD

**Issue by mstud** [TACC/Lmod#216]
When using .lua module files, the tab completion in zsh always completes to the entire filename, including the .lua extension. It should strip the .lua away, otherwise one will get an error when trying to load the module with .lua attached:

Lmod has detected the following error:  The following module(s) are unknown: "example.lua"

It is a bit of a hassle having to manually remove the .lua after using tab completion, so it would be highly appreciated if this could be fixed.
Does not happen with bash by the way, just zsh.

**Comment by rtmclay** [comment]
This has been fixed.  As of Lmod version 7.2.1, Lmod ships zsh tab completion files to work with the module command.  However they only work if they are installed.  When you get example.lua expanded all the way, it is because you are using the built-in zsh tab completion that works with Tmod and not Lmod.

**Comment by mstud** [comment]
I see, thank you, must have missed this during installation.
