### ISSUE TITLE
LMOD reloads deactivated modules in alphabetical order, triggering prereqs

### ISSUE THREAD

**Issue by vanderwb** [TACC/Lmod#223]
Using Lmod 7.2.1, I'm running into an error that is triggered by a script we have to load modules. Let's say I run the following module load:

module load python/2.7.13; module load numpy/1.12.0; module load netcdf4-python/1.2.7

The python module adds a modulepath that contains numpy and netcdf4-python. If I then remove python, numpy and netcdf4-python are deactivated as expected. When I then reload python, Lmod attempts to reactivate the modules in alphabetical order (or reverse or some unexpected order). Problem is, netcdf4-python has a prereq for numpy, and so the operation fails and I can't load python again unless I remove netcdf4-python explicity (or purge the whole thing).

**Comment by rtmclay** [comment]
I have pushed Lmod 7.3.14 to github to deal with this issue.  @vanderwb is correct previous to version 7.3.14,  inactive modules were sorted into alphabetical order.  Lmod 7.3.14 now remembers the "loadOrder" so that inactive modules are reloaded in the loading order.  

Please test 7.3.14 to see if it works for you.

**Comment by vanderwb** [comment]
Thanks for the quick reply and bug fix Robert. We will test it and confirm that it fixes the error for our module tree.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by vanderwb** [comment]
Hi Robert. Sorry for the delay. Yes, we've tested it and it works well. Please close.
