### ISSUE TITLE
Modification: update_lmod_system_cache_files

### ISSUE THREAD

**Issue by lewis-john-lloyd** [TACC/Lmod#232]
Would it be possible to have update_lmod_system_cache_files modify the contents of existing files instead of attempting to overwrite them?

**Comment by boegel** [comment]
Do you mean adding support for incremental cache updates?
As far as I know, the Lmod `spider` tool doesn't support this yet.

It's a feature I'm interested in too, in particular because this would allow us to let EasyBuild (quickly) update the Lmod cache, but it's unlikely I'll find time for this anytime soon...

**Comment by lewis-john-lloyd** [comment]
No, that is beyond the scope of what I would be interested in right now.
I am interested in having the update_lmod_system_cache_files routine open the cache file and its backup and modify the contents of those files in place if they exist as opposed to trying to cp over existing files.

**Comment by rtmclay** [comment]
The reason why it Lmod does it this way is so that the cache update can safely happen at any time.

1. Create a new cache file 
2. copy current_cache to old_cache
3. move new_cache current_cache

This is the only way I know to guarantee that trying to read the cache file can happen at anytime.
Lmod first looks for the current cache file then the old cache file.

**Comment by rtmclay** [comment]
I have some thoughts related to how one might speed up building the cache file that I'm going to send to the Lmod mailing list.   If you just read this and not the mailing list, you are missing out!

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by rtmclay** [comment]
No there is not.  It may still be some time before this new idea is tested.
