### ISSUE TITLE
Colorization issue

### ISSUE THREAD

**Issue by geimer** [TACC/Lmod#236]
After noting in the release notes of Lmod 7.1 that hidden modules should be "shown as dim", and actually seeing it on a colleagues machine, I was wondering why hidden modules are shown in the same style as regular modules for me.  Digging deeper I found that Lmod uses the ANSI escape code for "faint" (hard-coded).  But apparently, it is neither supported by KDE's `Konsole`, not by the good old `xterm` -- which maps with Wikipedia ("Not widely supported", see https://en.wikipedia.org/wiki/ANSI_escape_code).  Now I am wondering whether the "hidden color" could be made configurable.

**Comment by rtmclay** [comment]
The dim works well for me with a dark background for both xterm (MAC, Linux) and iTerm2 on a Mac.  It doesn't seem to work with dark letters over a white background.   Knowing that, I added the (H) marker so that it will be marked for all.  

Since I don't expect that most users will be trying to do "module --show_hidden avail" very often, I don't really see much need here but if you would like to work on this I'll look at a pull request for this.

**Comment by geimer** [comment]
You are right, xterm with white-on-black indeed works.  Weird...  For KDE's konsole, italics would be a viable alternative that works, so my point of having a configuration option (env var?) still applies -- especially since the coloring is also used for `module list` which I consider a command that many users will use from time to time.  But since I have **no** clue about Lua, don't expect a PR from me any time soon...

Another suggestion: Maybe the escape sequence should also be applied to the (H) marker as it is also some kind of property?

**Comment by rtmclay** [comment]
I decided to support this option.  By default Lmod uses faint for hidden modules. Lmod can now use italics instead.  Setting LMOD_HIDDEN_ITALICS=yes will change the output of hidden modules to use italics instead.  Lmod can also be configured to use italics instead of faint by building Lmod with ./configure --with-hiddenItalic=yes

Please pull HEAD to test this out for yourself when you get the chance.

**Comment by geimer** [comment]
Works great! Thanks!
