### ISSUE TITLE
tcsh problems with LMOD_FULL_SETTARG_SUPPORT undefined

### ISSUE THREAD

**Issue by gskouson** [TACC/Lmod#242]
If LMOD_FULL_SETTARG_SUPPORT isn't defined, loading the csh initialization results in errors:

```
$ tcsh -x /opt/lmod/lmod/init/csh
setenv LMOD_CMD /opt/lmod/lmod/libexec/lmod
setenv LMOD_DIR /opt/lmod/lmod/libexec
setenv LMOD_PKG /opt/lmod/lmod
setenv MODULESHOME /opt/lmod/lmod
set prefix = 
set midfix = 
set postfix = 
set merge = &&
set histchar = !
if ( 0 ) then
if ( 1 ) then
alias module eval `$LMOD_CMD tcsh  !*`  && eval `$LMOD_SETTARG_CMD -s csh`
else
alias clearMT eval `/opt/lmod/lmod/libexec/clearMT_cmd csh`
alias ml eval `/opt/lmod/lmod/libexec/ml_cmd !*`
setenv LMOD_VERSION 7.3.27
unset prefix
unset midfix
unset postfix
unset histchar
unset merge
if ( ! 1 ) then
LMOD_FULL_SETTARG_SUPPORT: Undefined variable.
```
The following patch fixes this problem for me:

```
--- /opt/lmod/lmod/init/csh     2017-03-15 13:29:37.000000000 -0700
+++ /opt/lmod/lmod/init/csh.fix  2017-03-15 14:20:33.420668521 -0700
@@ -20,7 +20,7 @@
   endif
 endif
 
-if ($?tcsh) then
+if ( $?tcsh  && $?LMOD_SETTARG_CMD ) then
   alias module  $prefix'eval `$LMOD_CMD tcsh '$midfix $histchar'*` '$postfix $merge' eval `$LMOD_SETTARG_CMD -s csh`'
 else
   alias module  $prefix'eval `$LMOD_CMD csh  '$midfix $histchar'*` '$postfix
@@ -41,7 +41,8 @@
   setenv TARG_TITLE_BAR_PAREN ""
 endif
 
-if ( $?TERM && $?prompt && $?tcsh && "$LMOD_FULL_SETTARG_SUPPORT" != no ) then
+if ( $?TERM && $?prompt && $?tcsh && $?LMOD_FULL_SETTARG_SUPPORT ) then
+  if ( "$LMOD_FULL_SETTARG_SUPPORT" != no ) then
    alias cwdcmd 'eval `$LMOD_SETTARG_CMD -s csh`'
 
    switch ($TERM)
@@ -51,6 +52,7 @@
          breaksw
       endsw
    endif
+  endif
 endif
 # Local Variables:
 # mode: shell-script
```

**Comment by rtmclay** [comment]
For csh/tcsh users the file /opt/apps/lmod/lmod/init/cshrc is supposed to be linked or copied to /etc/profile.d/z00_lmod.csh  and be loaded by the csh shell.  LMOD_FULL_SETTARG_SUPPORT is set there.  Please update your startup scripts.

**Comment by rtmclay** [comment]
After thinking about the real issue here, I have come up with a different solution.  Changes to Lmod startup that are controlled by configure should move from profile.in and cshrc.in should move to bash.in and csh.in.  This way the files called /etc/profile.d/z00_lmod.{csh,sh} that are copies of profile and cshrc should almost never change.  All the changes are in bash.in and csh.in.

I have done this.  There is now Lmod version 7.3.28 which implements the above.  Please make sure that your /etc/profile.d/z00_lmod.{sh,csh} files match profile and cshrc from 7.3.28.

If you get a chance please test Lmod 7.3.28.  Thanks!

**Comment by gskouson** [comment]
I tried 7.3.28 and it works for me now.  Thanks!
