### ISSUE TITLE
Hook inside hook

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#255]
I just noticed, when I call `LmodWarning` inside a hook (the load one to be precise), it doesn't call the `erWarnMsgHook`.

**Comment by rtmclay** [comment]
Inside Lmod, LmodWarning, LmodError, LmodMessage can be called in two different ways.  Either

```
    LmodWarning("Houston we have a problem....")
```
or 

```
    LmodWarning{msg="w_Failed_2_Find", ... }
```

It is only the second way that calls the hook errWarnMsgHook because only the second way has the all the arguments.  I'm unclear on how to convert the first way, which is essentially an array, to the second way which is a hash table.  

See src/MasterControl.lua at lines 577:593 (the l_generateMsg() function) if you have suggestions.

**Comment by wpoely86** [comment]
OK, I hadn't thought about that. I've switched to using the second form in our `SitePackage.lua`.

The only way of dividing the two cases that I can think about is checking if there is a `msg` key in the table? And the function then calls the correct subfunction?

**Comment by rtmclay** [comment]
I have thought about having a second errWarnMsgHook (say errWarnMsg2Hook) which would work but I don't like that.

Another way might be to take the ... side in l_generateMsg() and do:

```
   local key = false
   msg  = hook.apply("errWarnMsgHook", kind, key, arg) or msg
```

So if key is false then the implementor of errWarnHook would know that they have arg instead?

**Comment by rtmclay** [comment]
Closing this issue.
