### ISSUE TITLE
Highlight specific modules name

### ISSUE THREAD

**Issue by vanzod** [TACC/Lmod#282]
It may be useful to be able to highlight (e.g. by using bold font) some modules that give access to additional "layers" of software. For example, highlight compilers and MPI modules. In this way users can easily spot the available compilers or MPI libraries and load them to access all the modules built with that compiler/MPI.
This may be done in a similar way in which properties are defined and assigned to modulefiles.

**Comment by damianam** [comment]
We do that by creating an UI manually (well, actually with some scripts) and using a hierarchical module naming scheme. It looks like this: 

```
$ ml av
---- Packages compiled with ParaStationMPI and Intel compilers -----
   ABINIT/8.2.2                         ParaView/5.3.0-OSMesa
   AMBER/14-update13                    ParaView/5.3.0                     (D)
   ARPACK-NG/3.4.0                      PyMOL/1.8.6-Python-2.7.13
  [...]

------------ MPI runtimes available for Intel compilers ------------
   IntelMPI/2017.2.174          ParaStationMPI/5.1.9-1 (L,D)
   [...]
-------------- Packages compiled with Intel compilers --------------
   Eigen/3.3.3                 Libxc/2.2.3         ncview/2.1.7
   Embree/2.14.0               METIS/5.1.0         netCDF-Fortran/4.4.4-serial
 [...]
-------------------------- Core packages ---------------------------
   Advisor/2017_update2                    PostgreSQL/9.6.2
   AllineaForge/7.0.1                      PyGTK/2.24.0-Python-2.7.13
   AllineaPerformanceReports/7.0.1         PyOpenGL/3.1.1a1-Python-2.7.13
   Atom/1.15.0                             PyQt/4.12-Python-2.7.13
 [...]

---------------------------- Compilers -----------------------------
   GCC/5.4.0                     Intel/2017.2.174-GCC-5.4.0 (L,D)
   Intel/2016.4.258-GCC-5.4.0    PGI/17.3-GCC-5.4.0

----------------------- Recommended defaults -----------------------
   defaults/CPU (D)    defaults/GPU (g)
```

It is not exactly the same as you suggest, but it is similar. Alternatively, you can use properties, that even though don't change the font of the module, they highlight it.

**Comment by rtmclay** [comment]
I have had a chance to work on this issue.  Sites can now control whether or not the name is colorized or not.  I have added a new key to the display table for properties:

```
propT = {
   state = {
      validT = { experimental = 1, testing = 1, obsolete = 1 },
      displayT = {
         experimental  = { short = "(E)",  long = "(E)",  full_color = true,   color = "blue",  doc = i18n("ExplM"), },
         testing       = { short = "(T)",  long = "(T)",     color = "green", doc = i18n("TstM"), },
         obsolete      = { short = "(O)",  long = "(O)",     color = "red",   doc = i18n("ObsM"), },
      },
   },
   lmod = {
      validT = { sticky = 1 },
      displayT = {
         sticky = { short = "(S)",  long = "(S)",   color = "red",  full_color = true,  doc = i18n("StickyM"), }
      },
   },
```

This means that if you add `full_color=true` to a property display line, then the name will be colorized.  This means that a sticky module would have its name in red as well.  Also any module that sets the state to experimental will be colored blue. 

Since a module can have more than one property, you could try to set the module name to more than one color.  In this case you get the last property.  They are in alphabetical order by property name (i.e. state, lmod, ...).  So in this case where you have an experimental module that is also sticky (a weird case), it would be colored blue because state is later in the alphabet than lmod.

**Comment by vanzod** [comment]
@rtmclay Thank you for the addition. One clarification: are the `short` and `long` fields mandatory?

**Comment by rtmclay** [comment]
The `long` field is not currently being used.  The `short` field is required.

**Comment by vanzod** [comment]
Thank you Robert. You can close this issue.

**Comment by vanzod** [comment]
Thank you Robert.
