### ISSUE TITLE
Lmod crashes in fileOps.abspath when run from a deleted directory

### ISSUE THREAD

**Issue by rkdarst** [TACC/Lmod#292]
A user has just reported an interesting issue (the subcommand doesn't matter, crashes on startup):

```
/usr/bin/lua: /usr/share/lmod/lmod/libexec/../tools/fileOps.lua:354: bad argument #1 to 'chdir' (string expected, got nil)
stack traceback:
        [C]: in function 'chdir'
        /usr/share/lmod/lmod/libexec/../tools/fileOps.lua:354: in function 'abspath'
        /usr/share/lmod/lmod/libexec/utils.lua:685: in function 'readRC'
        /usr/share/lmod/lmod/libexec/lmod:517: in function 'main'
        /usr/share/lmod/lmod/libexec/lmod:711: in main chunk
        [C]: ?
```

I found that it occurs when Lmod is run from a deleted directory, and can be reproduced this way:
```
$ mkdir tmp
$ cd tmp
$ rm -r ../tmp
$ module
```
abspath: https://github.com/TACC/Lmod/blob/9074fd9731a1962c088dd8a53e8e79152e59faae/tools/fileOps.lua#L316
getcwd: https://github.com/TACC/Lmod/blob/9074fd9731a1962c088dd8a53e8e79152e59faae/pkgs/luafilesystem/lfs.c#L168

Root problem is: `fileops.lua:abspath` calls `cwd = lfs.currentdir()` and changes back at the end.  But if directory is deleted, the `cwd` is nil.  Attempting to call `lfs.chdir(cwd)` at the end fails.

This is perhaps a theoretical problem, but it occurred in this case because calculations were run in a temporary directory which was deleted while the script's cwd was still there.  A complicated solution (avoiding use of chdirs in abspath) is probably not worth the time, but at least it could trap this and print an error instead, or change back to home directory with error message saying what's happened.

Thoughts?

**Comment by boegel** [comment]
This is less theoretical than it sounds... Due to problems with NFS, I've run into the same problem here too, even though the working directory isn't actually deleted, it's just that Linux thinks it is.

+1 for better/cleaner error reporting, and I agree there's little else Lmod can/should do in this situation

**Comment by rtmclay** [comment]
It turns out that Lmod doesn't really need to do abspath in this place.  I found one other place that also fails if the current directory isn't valid.  I have tested "module list; module avail and module spider" with a non-valid directory and they all work now.  Lmod 7.5.7 is now ready for testing. Please let me know if this new version works for you.

**Comment by rkdarst** [comment]
OK, great.  Unfortunately we don't use Lmod distributed by upstream, and changing the  origin now is probably not a good use of time since the problem is so simple.  I trust that if it works there, it's solved.

Thanks,

- Richard
