### ISSUE TITLE
Exporting shell functions

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#313]
Hi!

I was wondering if there would be some interest in implementing a way to export the shell functions defined with `set_shell_function()`.

Right now, when loading a module, those functions are defined in the current shell, but are not available from children. So if, for instance, a user loads a module that defines `foo()`, then tries to call `foo()` from a script (say a batch job script), it won't work, as `foo()` won't be defined in the script.

A way to solve this would be to export the function with `export -f foo`, which will make it available from all the shell's descendants (I believe it is bash-specific though, I don't know if csh allows exporting functions). So if `set_shell_function()` implemented an option to automatically export functions, they would also be available in scripts called from the shell that loaded the module.

Thanks!

**Comment by rtmclay** [comment]
This is only true for bash shell scripts.  Bash interactive subshell should get the shell function defined from the parent.  Otherwise your startup scripts are broken.  See http://lmod.readthedocs.io/en/latest/070_standard_modules.html and read about "module refresh".

This is a bad idea.  It only works for bash users with bash scripts.  It doesn't work for zsh or tcsh/csh users.  Now it is not needed for them because of the way that those shells work.  It particular, ``export -f foo`` is an error in zsh. 

If users want their shell functions defined in batch job scripts, they should start their scripts with 

#/bin/bash -l

Note that is a minus ell, not minus one. This will cause the startup scripts to be run and if they are setup correctly, the shell functions from modulefiles will be available.

**Comment by kcgthb** [comment]
All right, that all makes sense. Thanks for the clarification!
