### ISSUE TITLE
Zsh autocompletion

### ISSUE THREAD

**Issue by rubendibattista** [TACC/Lmod#320]
Hello, I installed (out of standard tree `/usr/local`) 

lmod 7.7.6. 
zsh 5.4.1 (self compiled)

The part of the libexec/init script that does some checks before sourcing the bash completion file does not work:
```
if [ ${BASH_VERSINFO:-0} -ge 3 ] && [ -r  /home2/softmassot/lmod/lmod/init/lmod_bash_completions ] && [ -n "${PS1:-}" ]; then
    echo "This is not printed"
fi
```

Is this normal? So no autocompletion for zsh?

**Comment by rtmclay** [comment]
The bash tab completion file is for bash alone. $BASH_VERSINFO better not be defined under zsh. Zsh shell has its own completion files.  They are in the source in init/zsh/*.  If zsh is in your path when you install Lmod it will attempt to install the zsh completion files in the correct location.  Otherwise you'll need to copy _ml and _module files to the appropriate location for where your zsh is located.

Zsh is my personal shell and I use zsh tab completion for Lmod all the time.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by rubendibattista** [comment]
I still did not have the time to check, but I suppose it's gonna work as you suggest. Maybe give a bit more time to check if it's possible. Sorry for not giving a feedback before :)

**Comment by rtmclay** [comment]
O.K.  I check back next week.

**Comment by rubendibattista** [comment]
Moved the `_ml` and `_module` files that are in the source `init/zsh` to `~/.local/share/zsh/site-functions` (zsh is installed locally in the user `$HOME`). They work as expected. 

Thanks for the help!

**Comment by rtmclay** [comment]
You are welcome!
