### ISSUE TITLE
configure script fails to detect missing lua-filesystem

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#359]
When installing Lmod on a new system, I noticed that while `configure` spits out a clear error that `lua-posix` is missing:

```
Error: The follow lua module(s) are missing:  posix
```

it fails to do the same for `lua-filesystem`; instead `make` fails with:

```
/usr/local/Cellar/lua/5.3.4_3/bin/lua: ./src/spiderCacheSupport.in.lua:93: module 'lfs' not found:
	no field package.preload['lfs']
	no file './src/../tools/lfs.lua'
	no file './src/../tools/lfs/init.lua'
	no file './src/lfs.lua'
	no file '/usr/local/share/lua/5.3/lfs.lua'
	no file '/usr/local/share/lua/5.3/lfs/init.lua'
	no file '/usr/local/lib/lua/5.3/lfs.lua'
	no file '/usr/local/lib/lua/5.3/lfs/init.lua'
	no file './lfs.lua'
	no file './lfs/init.lua'
	no file './src/../lib/lfs.so'
	no file '/usr/local/lib/lua/5.3/lfs.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lfs.so'
stack traceback:
	[C]: in function 'require'
	./src/spiderCacheSupport.in.lua:93: in main chunk
	[C]: in ?
make: *** [spiderCacheSupport] Error 1
```

macOS, using `lua` installed by Homebrew

I was able to fix this issue using `luarocks install luafilesystem`.

**Comment by rtmclay** [comment]
I was able to reproduce this problem and fix it on my systems.  Since Lmod already provides a version of luafilesystem, there is no need to require users to install it first.  I just didn't get it right so that Lmod could be installed without LFS being installed there in the first place. This version (7.7.25) fixes this problem for me. 

Please test this new version to see if works for you.

**Comment by boegel** [comment]
Fix confirmed, thanks!
