### ISSUE TITLE
modulerc requires tclsh. Can we support modulerc files with lua syntax?

### ISSUE THREAD

**Issue by damianam** [TACC/Lmod#376]
We are deploying a new system and I am trying to avoid installing tclsh there. Probably I'll give up down the road but........ right now I'd like to avoid that. Anyway, it seems like modulerc just works with TCL syntax. Is it possible or reasonable to enable lua syntax there?

**Comment by rtmclay** [comment]
Sure, I am thinking about it.  Here is what I am thinking about:

Current commands are:

```
module-alias     name  modulefile
module-version   modulefile v1 v2 ...
hide-version     full_module_version
hide-modulefile  /path/to/modulefile
set ModuleVersion version
```
So the Lua based syntax could be:
```
module_alias("name","modulefile")
module_version("modulefile","v1","v2"...)
hide_version("full_module_version")
hide_modulefile("/path/to/modulefile")
```

I don't think I'll support the TCL set ModuleVersion ... syntax since
it is already available with module-version.  

So currently Lmod looks for the following files to set version:

1) default
2) .modulerc
3) .version

I would change this to:

1) .modulerc.lua
2) default
3) .modulerc
4) .version

So file named .modulerc would still be in TCL syntax and .modulerc.lua would be in lua syntax.

Comments?

**Comment by damianam** [comment]
Seems reasonable. Does it makes sense to support both `MODULERCFILE` and `MODULERCFILELUA`? Probably not...... but I thought I would raise the question

**Comment by rtmclay** [comment]
The env var variable MODULERCFILE will still point to the system modulerc file.  It will be the extension (i.e. *.lua or not) will determine whether this file is evaluated by tclsh or lua.  

Also a user can have either a ~/.modulerc or a ~/.modulerc.lua file.  Lmod will look for ~/.modulerc.lua then ~/.modulerc

I thinks that was your question.  If not please let me know.

**Comment by rtmclay** [comment]
I have uploaded 7.7.38 which has support for using Lua based .modulerc.lua files.  Please test this out to see if it works for you.

**Comment by rtmclay** [comment]
I am closing this issue.  If there are any problems please reopen this issue or create a new one.
