### ISSUE TITLE
warning messages in lmod - unloading non-existent modules

### ISSUE THREAD

**Issue by mcytowski** [TACC/Lmod#381]
Dear Lmod developers, 
would you accept a change similar to the one proposed here for Environment Modules: https://github.com/cea-hpc/modules/issues/187
Basically, it would be nice to have a warning message printed out e.g. when a given module does not exist and you are trying to unload it. Or in general: when you are trying to unload a module which is not loaded or load a module which is already loaded.
Kind regards,
Maciej Cytowski

**Comment by rtmclay** [comment]
I would prefer not to support this feature this way.  Lmod already has a tracing feature.  I have modified it so that it reports the state of the module Lmod is unloading:  active, inactive, non-existant

So if you do:

```
% module -T unload foo
running: module -T unload foo
  Unloading: foo (state: non-existant) (fn: nil)
```
I am assuming that you want this feature for debugging modulefiles.  In this case this seem reasonable to me. This feature is available in Lmod 7.8.4

**Comment by rtmclay** [comment]
I am closing this issue since it has been sitting for 16 days.

**Comment by mcytowski** [comment]
thanks for explanation and apologies for not replying earlier. And yes, it can be closed.
