### ISSUE TITLE
"module purge foo" is equivalent with "module --force purge"

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#397]
We discovered that calling `module purge` with any argument is effectively equivalent with `module --force purge`, which is quite confusing.

Example with a simple sticky module:

```
$ ml

Currently Loaded Modules:
  1) cluster/victini (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge

$ ml purge
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) cluster/victini

$ ml

Currently Loaded Modules:
  1) cluster/victini (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge


$ ml purge foo
$ ml
No modules loaded
```

**Comment by wpoely86** [comment]
I think the bug is on line 747 of `Master.lua`:
```
   if (masterTbl().force or force) then
```

The second part should be `force == true`

**Comment by rtmclay** [comment]
Thanks very much for the bug report and the fix.  It turns out that Ward, you are right in that line 747 in Master.lua is a problem.  But the reason why "force" as a value goes back a ways.  The trouble is that I used the Purge() routine in two ways.  One comes from a user, the other comes from the program.  The user side should never set the argument (force).  However, all command line arguments are always passed to user commands. To fix this I created a Purge_Usr() which is the command that users call which just calls Purge(). 

Please try Lmod 7.8.19 to see if it fixes your problem.  Thanks!

**Comment by boegel** [comment]
Works as expected with Lmod 7.8.19, thanks for the quick fix!

```
$ ml --version

Modules based on Lua: Version 7.8.19  2019-02-11 12:34 -06:00
    by Robert McLay mclay@tacc.utexas.edu

$ ml

Currently Loaded Modules:
  1) cluster/golett (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge

$ ml purge foo
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) cluster/golett

$ ml

Currently Loaded Modules:
  1) cluster/golett (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge

$ ml --force purge

$ ml
No modules loaded
```
