### ISSUE TITLE
tab completion does not work in a fish shell

### ISSUE THREAD

**Issue by asartori86** [TACC/Lmod#407]
Hi all, as reported in the title :)

```
$ module --version

Modules based on Lua: Version 8.0.9  2019-04-29 10:43 -05:00
    by Robert McLay mclay@tacc.utexas.edu

$ fish --version 
fish, version 3.0.2
```

**Comment by rtmclay** [comment]
Thanks for the suggestion but the fish shell is not a shell I use at all.  Therefore I have no expertise in creating a tab completion tool for fish.  

Please feel free to submit a pull request that will support tab completion for fish.  If you or any other fish shell expert have specific questions, I'll be happy to answer them.  You may find the tab completion source code for bash or zsh helpful in how to get information from the module system. 

In particular, you may find that "module --terse list", "module --terse avail" and "module --terse spider" helpful knowing what the module are currently loaded;  what modules are current available to load; and what modules can be "spidered".  Getting tab completion to work with "ml" is much more tricky because "ml li<tab>" could be ml list or ml linux, where linux is a modulefile.  There is some documentation in init/zsh/_ml to show you how I did it for zsh.

**Comment by asartori86** [comment]
thanks @rtmclay, indeed I realized last day that it was not implemented at all :)
