### ISSUE TITLE
Suggestion: rename set_alias() to push_alias(), cf. pushenv() and setenv()

### ISSUE THREAD

**Issue by HenrikBengtsson** [TACC/Lmod#425]
AFAIU, `set_alias()` will undo the alias when the module is unloaded.  In contrast, `setenv()` is not undone, whereas `pushenv()` is.

I'd like to propose "renaming" `set_alias()` to `push_alias()` to reflect that the alias is undone.  I understand that `set_alias()` needs to be kept around for backward compatibility, but eventually it could be deprecated, e.g. hiding it from the document and so on.

PS. I was just (re-)bitten by using `setenv()` instead `pushenv()` just because I used `set_alias()` on the line above.  Not the first time.

**Comment by rtmclay** [comment]
Here is what Lmod does:

function        Load Action         Unload Action
set_alias        set_alias              unset_alias
setenv .          setenv                 unsetenv
pushenv .       pushenv             popenv

The functions setenv() and set_alias() define something on load and are unset on unload.  Pushenv maintains a stack hidden in the environment so that the old value can be retrieved.  There is no stack for either setenv or set_alias.  

So unloading a module with a set_alias('foo', ....) will remove the alias for "foo".  It will not reset it back to the previous definition of 'foo'.

Also set_alias() has been around a long time.  I wouldn't rename it.  It would break too many modulefiles.

**Comment by HenrikBengtsson** [comment]
> So unloading a module with a set_alias('foo', ....) will remove the alias for "foo". It will not reset it back to the previous definition of 'foo'.

Ah... this is an important difference that I missed.  Thank you for clarifying this!

> Also set_alias() has been around a long time. I wouldn't rename it. It would break too many modulefiles.

Righty'oh, my suggestion was to create an "alias" for it so that it could be used.  But since it does not push/pop the alias in the first place, my suggestion is moot.
