### ISSUE TITLE
bash tab completion for module doesn't work in sub-shell

### ISSUE THREAD

**Issue by site-g** [TACC/Lmod#468]
The bash tab completion for module stop working every time I start a new bash shell or tmux in bash. I have to source ` /PATH/TO/LMOD/8.2.5/init/bash` to make it work again. The auto completion for other softwares work well.
Is this normal?

**Comment by rtmclay** [comment]
In my view, bash has a bad design when it comes to interactive shells versus login shells.  You can read about it here:

https://lmod.readthedocs.io/en/latest/030_installing.html#issues-with-bash

**Comment by site-g** [comment]
Is it safe to source `/etc/profile.d/lmod.sh` multiple times? I think the best workaround should be source that file in system bashrc (My distribution has system bashrc). Or is there something like an environment variable that can be used to check if lmod (and the auto-comp) has been loaded?

**Comment by rtmclay** [comment]
You can of course source /etc/profile.d/lmod.sh on each shell but is there a reason why you can't follow the suggestion:

```
if [ -f /etc/bashrc ]; then
   . /etc/bashrc
fi
```

Which will do the same thing.  You may have to change /etc/bashrc to something else to match your system.  This of course assumes that /etc/bashrc sources all the files *.sh in /etc/profile.d.  Mac OS doesn't work that way so your solution maybe the best for you.

**Comment by site-g** [comment]
We do have those lines already now. Basically other programs' auto-comp works fine, so I suppose that `profile.d/*` was either re-executed or inherited from the parent bash process, when I start a sub bash shell in an ssh-logged bash she'll.
[bashrc.zip](https://github.com/TACC/Lmod/files/5287596/bashrc.zip)

**Comment by rtmclay** [comment]
Thanks for the zip file with your startup behavior.  Are you on Cray with Lmod as a system install? In any event, this is a bug in the startup behavior of your SuSE system.  If you look at the bash.bashrc that you sent, you'll see that they the startup shell doesn't re-source /etc/profile.d on sub-shells.  Instead they do source  the bash completion file.

So the answer to your question.  Yes, this is normal, tab completion for Lmod doesn't get sourced for sub-shells for your particular system (SuSE based).  It is not a bug in Lmod.  To fix this for all users, the site could fix this by adding the source of lmod bash completion file to /etc/bash.bashrc.local. 

I believe this is a bug in the way that SuSE handle startup behavior.  On our Cray (which is SuSE based), I have rewritten the startup scripts to work more like the way that Redhat does it.  If this is a Cray, it would be worth submitting a bug report to them because this is new and they may respond.

**Comment by site-g** [comment]
Thanks. As `/etc/profile` writes just after sourcing all `profile.d` scripts (line 314),

```shell
#
# Avoid overwriting user settings if called twice
#
if test -z "$PROFILEREAD" ; then
    readonly PROFILEREAD=true
    export PROFILEREAD
fi
```

I believe the behaviour is intended. For now the only way to fix it on SuSE based systems would be sourcing `/etc/profile.d/lmod.sh` in bash.bashrc.local manually.
