### ISSUE TITLE
Default module not marked when submodules/subfolders inside

### ISSUE THREAD

**Issue by kmanalo** [TACC/Lmod#47]
At our site we have a flat tree structure, save for the intel suite.  I'm having a hard time trying to mark intel/15.0.0 as my default (tried the symlink to default, currently using .version for back-compatibility):

TCL modules reports:
<pre>
------------ /path/to/modulefiles ------------
intel/10.1.013                intel/ifort/11.1.072
intel/11.0.083                intel/ifort/12.1.1.256
intel/11.1.038                intel/ifort/13.0
intel/11.1.046                intel/ifort/14.0.2
intel/11.1.072                intel/ifort/15.0.0(default)
intel/12.1.1.256              intel/ifort/15.0.1.133
intel/13.0                    intel/ipp/6.0.2
intel/14.0.2                  intel/ipp/6.1.0
<b>intel/15.0.0(default)</b>         intel/ipp/6.1.1
intel/15.0.1.133              intel/ipp/6.1.5
intel/icc/10.1.013            intel/ipp/7.0.5.256
intel/icc/11.0.083            intel/ipp/7.1
intel/icc/11.1.038            intel/ipp/8.1
intel/icc/11.1.046            intel/ipp/8.2.0.090(default)
intel/icc/11.1.072            intel/ipp/8.2.1.133
intel/icc/12.1.1.256          intel/mkl/10.1.1
intel/icc/13.0                intel/mkl/10.2.0
intel/icc/14.0.2              intel/mkl/10.2.2
intel/icc/15.0.0(default)     intel/mkl/10.2.5
intel/icc/15.0.1.133          intel/mkl/10.3.7
intel/idb/10.1.013            intel/mkl/11.0
intel/idb/11.0.083            intel/mkl/11.1.2
intel/idb/11.1.038            intel/mkl/11.2.0.090(default)
intel/idb/11.1.046            intel/mkl/11.2.1.133
intel/idb/11.1.072            intel/tbb/2.1.2
intel/idb/12.1.1.256          intel/tbb/2.1.4
intel/idb/13.0                intel/tbb/2.2.2
intel/idb/13.0.80.483.23      intel/tbb/4.0.1
intel/ifort/10.1.013          intel/tbb/4.1
intel/ifort/11.0.083          intel/tbb/4.2.3
intel/ifort/11.1.038          intel/tbb/4.3.0.090(default)
intel/ifort/11.1.046          intel/tbb/4.3.2.135
</pre>

Lmod reports:
<pre>
--------------------------------------------------------------------------------------------------------- /path/to/modulefiles ---------------------------------------------------------------------------------------------------------
   intel/10.1.013      intel/15.0.1.133        intel/icc/15.0.0     (D)    intel/idb/13.0.80.483.23 (D)    intel/ifort/15.0.0     (D)    intel/ipp/8.2.0.090 (D)    intel/mkl/11.2.0.090 (D)    intel/tbb/4.3.2.135
   intel/11.0.083      intel/icc/10.1.013      intel/icc/15.0.1.133        intel/ifort/10.1.013            intel/ifort/15.0.1.133        intel/ipp/8.2.1.133        intel/mkl/11.2.1.133        opencl-intel/1.2
   intel/11.1.038      intel/icc/11.0.083      intel/idb/10.1.013          intel/ifort/11.0.083            intel/ipp/6.0.2               intel/mkl/10.1.1           intel/tbb/2.1.2
   intel/11.1.046      intel/icc/11.1.038      intel/idb/11.0.083          intel/ifort/11.1.038            intel/ipp/6.1.0               intel/mkl/10.2.0           intel/tbb/2.1.4
   intel/11.1.072      intel/icc/11.1.046      intel/idb/11.1.038          intel/ifort/11.1.046            intel/ipp/6.1.1               intel/mkl/10.2.2           intel/tbb/2.2.2
   intel/12.1.1.256    intel/icc/11.1.072      intel/idb/11.1.046          intel/ifort/11.1.072            intel/ipp/6.1.5               intel/mkl/10.2.5           intel/tbb/4.0.1
   intel/13.0          intel/icc/12.1.1.256    intel/idb/11.1.072          intel/ifort/12.1.1.256          intel/ipp/7.0.5.256           intel/mkl/10.3.7           intel/tbb/4.1
   intel/14.0.2        intel/icc/13.0          intel/idb/12.1.1.256        intel/ifort/13.0                intel/ipp/7.1                 intel/mkl/11.0             intel/tbb/4.2.3
   <b>intel/15.0.0</b>        intel/icc/14.0.2        intel/idb/13.0              intel/ifort/14.0.2              intel/ipp/8.1                 intel/mkl/11.1.2           intel/tbb/4.3.0.090  (D)
</pre>

On 'Version 5.8.1 (5.8.1-1-g2fef574) 2015-01-07 10:06'

Recommendations?

**Comment by rtmclay** [comment]
You have a problem because of your layout of modules.  As far as Lmod is concerned, intel/15.0.0 is "meta-module" that is it is a module which has no version. This also means that there can be no default as well.   Lmod uses the rule that "versions" can only exist in a directory where that directory has no sub-directories.  Obviously "." and ".." don't count.

This layout doesn't make sense to me.    You'd could never expect that a user could mix intel/icc/10.1.013 and intel/idb/12.1.1.256 etc and expect it to work.   Presumably users only ever load intel/11.0.083 and the 11.0.083 module loads intel/icc/11.0.083 and intel/idb/11.0.083, etc.   You could merge the intel/icc/* intel/idb/* etc module files into the appropriate intel/version modulefile and the problem would go away.

Lmod is not the same as TCL/C modules.   Lmod stretches in certain directions.  In my view TCL/C allows for some things which Lmod doesn't support and shouldn't.  You may view things differently. It is interesting to note that this is the second time today that the issue of the "one-name" rule has come up.

**Comment by kmanalo** [comment]
Thanks for explaining; this layout predates my management of it, but I'll take your points in and see if I can absorb the components into the base intel; I'm not sure why it was laid out this way initially either.  Also, just clarifying what TCL/C modules vs. Lmod is helpful in this instance.

**Comment by rtmclay** [comment]
I believe the reason was that intel used to provide separate packages for each product.  At about intel/13. they switched to a single package which had everything.   As a side node, we have dropped the last number from our version.   We call intel/15.0.1 and not intel/15.0.1.133.  Intel has never released 15.0.1.x and 15.0.1.y.  Also I like to match the version of the module with the output version from "icc -dumpversion"
