### ISSUE TITLE
reversing `remove_path()` on unload?

### ISSUE THREAD

**Issue by alextruong** [TACC/Lmod#506]
Hello! I'm designing a modulefile that is attempting to hide the current (default) set of modulefiles and expose a new set, which also respects user-added paths on `MODULEPATH`. I've got something along the lines of, e.g. test.lua

```
if (mode() == "load") then
    prepend_path("MODULEPATH", "/new/path")
    remove_path("MODULEPATH", "/default/path1")
    remove_path("MODULEPATH", "/default/path2")
end

if (mode() == "unload") then
    LmodMessage("is this working?")
    remove_path("MODULEPATH", "/new/path")
    append_path("MODULEPATH", "/default/path1")
    append_path("MODULEPATH", "/default/path2")
end
```

However, it seems that while the load block works, the unload block does not (LmodMessage() does print, so it's definitely entering the block). I noticed that in https://github.com/TACC/Lmod/blob/75238c866c0dace01c04dfbb32ff165236b30c6d/src/MC_Unload.lua#L77, it refers to itself instead of something like `append_path()` or `prepend_path()`. Is this intentional? When I try the above example, I get the following sort of behavior:

```
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2
$ module load test
$ echo $MODULEPATH
/new/path:/my/custom/path
$ module unload test
is this working?
$ echo $MODULEPATH
/new/path:/my/custom/path
```

Admittedly our environment is on a pretty old version of Lmod (7.5.17), so I can't say for sure if this has been addressed in a later version.

I originally just tried a modulefile without the if statements, so just (e.g. test2.lua)

```
prepend_path("MODULEPATH", "/new/path")
remove_path("MODULEPATH", "/default/path1")
remove_path("MODULEPATH", "/default/path2")
```

but that had similar behavior, even though it appears that https://github.com/TACC/Lmod/blob/75238c866c0dace01c04dfbb32ff165236b30c6d/src/MC_Unload.lua#L73 , which makes sense:

```
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2
$ module load test2
$ echo $MODULEPATH
/new/path:/my/custom/path
$ module unload test2
/my/custom/path
```
 Now that I'm thinking about it, I suppose that functions inside of if statements don't get "reversed" for obvious reasons, I guess? What would be a good solution to this? Thanks!

**Comment by rtmclay** [comment]
Most module functions get reversed when unloading.  There are some that can't be reversed during unloading.  The remove_path() function is one of them.  

I am not sure what you want to do.  Rather than have me guess, please be specific about what the MODULEPATH should be before and after.  Also what happens to the previously loaded modules?

**Comment by alextruong** [comment]
I basically have a default stack of modules, and a separate, mutually exclusive stack of modules. I'd like to write a modulefile that would manipulate MODULEPATH accordingly so that the user can only see one or the other (with the addition of any manually user-added paths for stuff they're created themselves or whatever). So, basically, I'd like the behavior to be something like :

```
$ echo $MODULEPATH
/default/path1:/default/path2
$ module use /my/custom/path
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2
$ module load fancy_module
$ echo $MODULEPATH
/new/path:/my/custom/path
$ module unload fancy_module
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2
```
Previously loaded modules that are part of the stack being hidden should be rendered unusable (e.g. unloaded); they don't have to be reloaded upon unloading the magic module.

**Comment by alextruong** [comment]
I suppose that upon further thought, I'd need some sort of fixed path where this module would live so that it doesn't hide itself, actually - 

```
$ echo $MODULEPATH
/default/path1:/default/path2:/fixed/path
$ module use /my/custom/path
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2:/fixed/path
$ module load fancy_module
$ echo $MODULEPATH
/new/path:/my/custom/path:/fixed/path
$ module unload fancy_module
$ echo $MODULEPATH
/my/custom/path:/default/path1:/default/path2:/fixed/path
```

**Comment by rtmclay** [comment]
What would a remove_path reverse to?

When we have had to do something similar, we have used shell commands to change $MODULEPATH.  I would recommend that you do something like a shell function that does:

```
module purge
clearMT
export MODULEPATH=....
export LMOD_SYSTEM_DEFAULT_MODULES=...
module reset
```

If you are interested in proceeding with a Lmod modulefile solution then you can create a function 
that does what you want by creating a SitePackage.lua file.  See: https://lmod.readthedocs.io/en/latest/250_site_package.html?highlight=SitePackage.lua   

You could also use the family() function to have a "standard" modulefile and "fancy" modulefile define the different $MODULEPATH

You place standard.lua and fancy.lua in /fixed/path and place them both in the same family (say MPATH_FOO).  Then standard prepends /default/path1 etc to MODULEPATH.  And fancy.lua does prepend_path("MODULEPATH","/fancy/path").  When standard is loaded first and then fancy is loaded second then /default/path1 etc will be removed and /fanch/path will be added.
Reloading "standard" will remove /fancy/path and load /default/path1 etc because they are in the same family.

Use the shell script version when you expect users to switch to one and not come back.  Use the family() approach if you think that users will switch back and forth. Creating your own function(s) should be a last resort.

**Comment by alextruong** [comment]
Ah, that's true, using family would solve the path juggling issue; however, the standard modules need to be available by default, as opposed to users logging in to only see "standard" and "fancy", since many users in our environment load modules from the standard stack in their init scripts. We could make the standard modulefile sticky and load it in the global init files, but that seems...heavy handed, and could possibly break stuff we don't know about that users have set up independently. That said, I can't think of any situation where that might be the case off the top of my head...

**Comment by rtmclay** [comment]
I'm not sure what else I can tell you.  Is there anything else?

**Comment by alextruong** [comment]
To clarify, is it the case that upon module unload, anything in the modulefile that is expected to run is automatically reversed? To illustrate, I had in the first provided code block above a `prepend_path()` in the `if (mode() == "unload")` block, but clearly no prepending is happening. I can only presume that it's trying instead to reverse that operation, and thus the MODULEPATH variable is remaining unchanged because that path didn't exist anyway.

**Comment by rtmclay** [comment]
Yes.  In the case of unloading.  remove_path() tries to remove things.  Append_path() is reversed to do a remove_path().
There is no way to prepend_path or append_path from a modulefile during an unload.

**Comment by rtmclay** [comment]
O.K. to close?

**Comment by alextruong** [comment]
> 
> 
> O.K. to close?

ah, sorry, for some reason my view of the issue didn't update with this message until after I posted the above comment. Pending that, I suppose it's fine to close.

**Comment by rtmclay** [comment]
Please read: https://lmod.readthedocs.io/en/latest/170_hooks.html?highlight=LMOD_PACKAGE_PATH#how-to-set-up-sitepackage-lua.  It describes how to have a SitePackage.lua in any location you like.

Closing this issue now.
