### ISSUE TITLE
Error using print() in lua modulefiles

### ISSUE THREAD

**Issue by cniethammer** [TACC/Lmod#507]
I am using 
> $LMOD_CMD  --version
> Modules based on Lua: Version 8.2  2019-10-30 11:17 -05:00

According to "How does one debug a modulefile?" in the FAQ entry https://lmod.readthedocs.io/en/latest/040_FAQ.html one can use `print()` inside lua modulefiles for output. However I get the following error when doing so:
```
module load apptest/test
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     modulefiles/apptest/test.lua: [string "print("Hello OK");..."]:1: attempt to call a nil value (global 'print')
     Please check the modulefile and especially if there is a the line number specified in the above message 
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    apptest/test     modulefiles/apptest/test.lua
```

**Comment by rtmclay** [comment]
I always use io.stderr:write() instead and never had tested using print().  As of Lmod 8.4.28 you can now use print().

Please test version 8.4.28 to see if if works for you.

**Comment by cniethammer** [comment]
Thanks for the fast response and release update. I miss some of the required lua dependencies on the target system to build from source at the moment. As soon as they are met I'll give it a try.

**Comment by rtmclay** [comment]
I am closing this issue.  If there anything related to this, please feel free to re-open.

**Comment by ernstki** [comment]
Hi, all. I'm stuck with Lmod 7.x, for the time being, on one of the clusters where I do work. Was there already some facility in Lmod for sourcing an existing shell script into the running environment, such as a Bash auto-completion setup script?

Without the ability to `print` in Lmod, I can't seem to figure it out. Maybe I missed something in the docs?

For example, in Modules, I had been using `puts` for that, like

```tcl
# source the Bash programmable completion script
puts "source $topdir/bash-completion.d/*.bash;"
```

…and I think that semicolon at the end is/was required, so it wouldn't run together with the other commands being `eval`d.

Just as an aside, it _looks_ like Modules has `source-sh` [as of 4.6](https://modules.readthedocs.io/en/latest/MIGRATING.html#source-sh-modulefile-command), which actually tracks the changes to the environment, then backs out of them when the module unloads. I'm not even looking for that, just some way to do `source` from an Lmod modulefile.

**Comment by rtmclay** [comment]
You can use ```execute{}```  function from Lua modulefiles or as you use puts "...." inside a TCL modulefile to "source" things.  See: https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html?highlight=execute#extra-functions for details

See https://lmod.readthedocs.io/en/latest/160_debugging_modulefiles.html for how to debug modulefiles

Note that print() or io.stdout:write() statement do "work" it is just that they get "eval"d instead of printing to the terminal.  You should use io:stderr:write() instead.

I'll look at source-sh from Tmod to see if it would be useful.

**Comment by ernstki** [comment]
Thanks for the note on `execute{}`, I can look into that. As a last resort, I'd also be OK with rewriting the affected modulefiles in Tcl, since they're relatively simple apart from the need to `source` an external script.

> Note that print() or io.stdout:write() statement do "work" it is just that they get "eval"d instead of printing to the terminal. You should use io:stderr:write() instead.

I really _did_ intend to use `print` or `io.write:stdout` for exactly the purpose you mention, to `eval` the output. I think it's a moot point now that you mention `execute{}`;  however, with Lmod 7.8.22, I get


```tcl
print("source " .. topdir .. "/etc/bash-completion.d/ascli.bash;")
# --> […] attempt to call global 'print' (a nil value)
```

or 

```tcl
io.stdout:write("source " .. topdir .. "/etc/bash-completion.d/ascli.bash;")
# --> […] attempt to index field 'stdout' (a nil value)
```

I get that 7.x is pretty far behind the latest version, and maybe both of those have been implemented/fixed in 8.x, but I'm not in charge of the HPC site in question, so what version of Lmod is used is out of my control, sadly.

I think I've got more than enough to go on, and thank you kindly, sir! Cheers.

**Comment by rtmclay** [comment]
You are correct.  Lmod 7+ did not support print or io.stdout:write.  Version 8+ does.

**Comment by ernstki** [comment]
And

```tcl
execute{
    cmd="source " .. topdir .. "/etc/bash-completion.d/ascli.bash",
    modeA={"load"}
}
```

indeed does the trick. Thanks.
