### ISSUE TITLE
lmod tracking: data_to_db():  'user'

### ISSUE THREAD

**Issue by eylenth** [TACC/Lmod#520]
Hi 

We are using the lmod tracking system for 2 years now, but suddenly we encounter the following issue when [step 6 ](https://lmod.readthedocs.io/en/latest/300_tracking_module_usage.html#step-6) is executed: 

```bash
[root@by0owm] ~ # /bin/bash /tools/general/lmod/store_module_data_cron.sh
data_to_db():  'user'
data_to_db():  'user'
data_to_db():  'user'
data_to_db():  'user'
```

I have also tried to recreate the database, but it didn't help.
probably it is something related with the user of the lmod database or the users of the that are loading the modules ?

**Comment by rtmclay** [comment]
Please send me (via email) a syslog file that files.  Please split the syslog file in half and again to get the size to something small that fails  (say no more than 1000 lines). What I mean by this is to take the large syslog file and split it in half and try to import each half.  Pick the half that fails and split it half again and keep doing that until you have a small enough failure case.

Since you have had this tracking working for 2 years, it is likely that there is something special about one or more of the lines in the syslog file.

My guess is that you have a user name which has a non-ASCII UTF-8 character in their name.  (e.g. RœB∑rt).
But I won't know unless I have some data to test.

**Comment by rtmclay** [comment]
I have made some changes to the store_module_data and LMODdb.py files.  You can now get better tracking of what is happening during the storing of the Lmod records.  I tested this with at user named: RœB∑rt and it works fine.  To adding debugging statements please add the -D option.

``` 
$ ./store_module_data -D moduleUsage.log
  --> Trying to connect to database
  --> Build userT
  --> Insert into userT
  --> build moduleT
  --> get mod_id
  --> Insert into join_user_module Table for user: RœB∑rt
```

**Comment by eylenth** [comment]
I Found the issue
Something it could happen that there isn't an user defined in the moduleUsageFile
user= 

I have updated the SitePackage.lua  that an empty USER variable should not be tracked 

Issue can be closed
Thank you for the tip for filtering out the syslog file until I see the issue.

**Comment by rtmclay** [comment]
Glad I could help.  Closing this issue.

**Comment by Jackcurious** [comment]
Sorry for opening up a close thread @eylenth can you share your code how to fix the this issue.
