### ISSUE TITLE
tcl2lua.tcl creates delim= keyword argument, not sep=

### ISSUE THREAD

**Issue by zerothi** [TACC/Lmod#527]
In the documentation it seems the argument for the `prepend_path`/`append_path` uses `sep=`, see here: https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html

However, the `tcl2lua.tcl` script creates the keyword `delim=` https://lmod.readthedocs.io/en/latest/160_debugging_modulefiles.html?highlight=delim#tcl-modulefiles

Also, it is a bit annoying it adds the `priority=0` keyword even if priorities are not defined in the tcl script. I know this is just simpler, but perhaps it complicates things for the end-users too much?

**Comment by rtmclay** [comment]
It is true that the Lua module documentation uses the word "sep" and the TCL modulefiles use --delim.  This is because I figured out that I needed support for a different character separator before I found out that TCL modulefiles already supported --delim.  

I have modified the TCL documentation to describe what Tmod already supported. I have also added documentation for priority for TCL modulefiles.   The script ```tcl2lua.tcl``` does support and has supported the priority argument.  There is no keyword support in TCL modulefiles for priorities.  It is just the optional last argument.

To be consistent between Lua modulefiles and TCL modulefiles, I have switch the "sep" name to "delim" name in the documentation for both.  Note that previously, Lmod has just used the word "sep" as a name and not as a key.  So changing the word "sep" to "delim" doesn't change anyone modulefiles just what that positional argument is called. Internally Lmod has used "delim" as that name of the key. 

Does this clarify the issue for you?  Please see the updated documentation.

**Comment by zerothi** [comment]
> It is true that the Lua module documentation uses the word "sep" and the TCL modulefiles use --delim. This is because I figured out that I needed support for a different character separator before I found out that TCL modulefiles already supported --delim.
> 
> I have modified the TCL documentation to describe what Tmod already supported. I have also added documentation for priority for TCL modulefiles. The script `tcl2lua.tcl` does support and has supported the priority argument. There is no keyword support in TCL modulefiles for priorities. It is just the optional last argument.

Thanks. I think since the table argument can be used `append_path{...}` it is vital that they match in terms of argument names. So great you fixed this.

> To be consistent between Lua modulefiles and TCL modulefiles, I have switch the "sep" name to "delim" name in the documentation for both. Note that previously, Lmod has just used the word "sep" as a name and not as a key. So changing the word "sep" to "delim" doesn't change anyone modulefiles just what that positional argument is called. Internally Lmod has used "delim" as that name of the key.
> 
> Does this clarify the issue for you? Please see the updated documentation.

Please see my PR #529 for some additional tweaks and documentation fixes. Hope they fit in?

**Comment by zerothi** [comment]
Thanks, all is good now!
