### ISSUE TITLE
unloading Tcl module file that uses pushenv does not restore original value of environment variable

### ISSUE THREAD

**Issue by boegel** [TACC/Lmod#584]
**Describe the bug**

Unloading a module file in Tcl syntax that uses `pushenv` does not restore previous value of the environment variable.
 
**To Reproduce**

```shell
$ mkdir -p /tmp/$USER/modules/test
$ echo '#%Module' > /tmp/$USER/modules/test/1.2.3
$ echo 'pushenv TEST 123' >> /tmp/$USER/modules/test/1.2.3
$ module use /tmp/$USER/modules

$ export TEST=0
$ echo $TEST
0
$ module load test/1.2.3
$ module list

Currently Loaded Modules:
  1) test/1.2.3

$ echo $TEST
123

$ module unload test/1.2.3
$ module list
No modules loaded
$ echo $TEST
123
```

**Expected behavior**

Value of `$TEST` is restored to original value.
In example above:  `0` (not `123`) when `test/1.2.3` module is unloaded.

**Desktop (please complete the following information):**
 - OS: Linux / macOS
 - Linux distribution: RHEL 8.4 / macOS 12.4
 - Lmod Version: 8.7.4 / 8.7.3

**Additional context**

*(nothing in particular)*

**Comment by rtmclay** [comment]
This bug has existed ever since Lmod integrated the TCL library.  The issue is that now the TCL evaluation happens in the same environment as Lmod.  The **pushenv TEST 123** gets evaluated and pushed to the environment.  Then when Lmod runs it uses 123 again as the old value.  The fix is to have the program tcl2lua.tcl remember the changes it made to the env. before ending the TCL evaluation of the modulefile.

I was able to reproduce your issue and fix it for me.  Please test Lmod 8.7.6 to see if it works for you.

**Comment by boegel** [comment]
Sorry for not getting back to this yet. I can confirm that Lmod 8.7.6 fixed the problem I reported here (see also https://github.com/easybuilders/easybuild-framework/pull/4030, where the Lmod version we're testing with was bumped)
