### ISSUE TITLE
MANPATH is not restored exactly after purge

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#590]
On our system (Lmod 8.7.4):

```
$ echo $MANPATH
:
$ ml foss
$ echo $MANPATH
/apps/brussel/CO7/skylake/software/zlib/1.2.11-GCCcore-11.2.0/share/man:/apps/brussel/CO7/skylake/software/GCCcore/11.2.0/share/man::
$ ml purge
$ echo $MANPATH
::
```

So the original value of `:` gets 'doubled'.  Is this some Lmod magic around `MANPATH`? Is this intentional? It's not really a big issue but the final environment is not identical to original one.

**Comment by rtmclay** [comment]
Yes it is intentional.  There is no special magic for $MANPATH, but there is magic about `:`  As you probably know $MANPATH needs a trailing colon to find the system MANPATH.  So Lmod has to honor that.  But to do that Lmod has remember a nothing path at the end.  Also LUA_PATH needs a `;;` at the end to find the system LUA_PATH.  So Lmod treats all env. vars like that by doubling the separator.

**Comment by rtmclay** [comment]
Closing this issue.  If you have more questions, please feel free to re-open.
