### ISSUE TITLE
Can't get --pin-versions to work on HPE/Cray

### ISSUE THREAD

**Issue by pawsey-kbuckley** [TACC/Lmod#707]
Before I start, I need to point out that I'm running this on a HPE/Cray box,
and so it so possible that one, or both, of them may have mangked things
along the way.

Recently came across the Lmod issue, 59, from back in 2015, where the
  `--pin-versions`
functionality was added.

Hadn't heard of it before, but It seemed like it might have been the answer
to the problem I was looking into: Deep Joy.

I tried to use it: Deep Sorrow

Doing this
```
 ml --pin_versions save cray-cce
```
just throws back the "usage" page, although there's no mention
of the `--pin-versions` option in there.

The version is use reports itself as being
```
$ ml --version

Modules based on Lua: Version 8.7.19  2023-01-17 10:45 -06:00
    by Robert McLay mclay@tacc.utexas.edu
```
and, by following my nose from this
```
$ type ml
ml is a function
ml () 
{ 
    eval "$($LMOD_DIR/ml_cmd "$@")"
}
```
I can see that the `ml_cmd` does indeed have the `--pin-versions` option
within the file, however, the equivalent  `eval` in the above, results in
```
$ lua /opt/cray/pe/lmod/lmod/libexec/ml_cmd --pin_versions save cray-cce
module --pin_versions save  'cray-cce'
```
so I am guessing that it's the `module` command, but not `ml`, that's
not supporting the `--pin-versions` option.

Any thoughts on why it wouldn't do that ?

I have workarounds (yes: plural) for the issue, but it seems as though
telling Lmod to load an explicit set of modules, versions and all,
which is what I read the `--pin-versions` option as doing, for a 
`save` and a `restore`, shoudn't be able to do the "wrong thing": but
maybe it can, and it's been turned off?

Kevin Buckley
Supercomputing Systems Administrator
Pawsey Supercomputing Centre

**Comment by rtmclay** [comment]
The `ml` command is just a convenience. All it does is to save me typing the very long `module` command (;->).  All 
the comand does is generate the appropriate `module` command. Sometimes it takes a while for me to remember to add module options to the ml command. Especially for options I don't normally use. 

All I can say is that `ml --pin_versions --show save` does the right thing now for the current version of Lmod.   Also if pin_version is what you want. Why not set $LMOD_PIN_VERSIONS?

**Comment by pawsey-kbuckley** [comment]
>Why not set $LMOD_PIN_VERSIONS?

Because of the assumption that if `module,`when having the commandl ine
argument passed to it, via `ml`, wasn't respecting it, then it probably wouldn't
respect the EnvVar, which I had read about, either.

What I can tell you is setting it doesn't see any refusal to do anything, bar 
presenting me with the help page.

If it has done the right thing, is there any difference in the saved files that
I can look for to verify that?

Oh yeah, whilst I have you, the save/recover files appear to be created in
TWO places: `$HOME/.lmod` and `$HOME/.config/lmod`yet I can remove
a file from below `$HOME/.lmod`  and `savelist` will still report the list from
`$HOME/.config/lmod`.

So why the duplication?

**Comment by rtmclay** [comment]
Please read https://github.com/TACC/Lmod/issues/595 to learn about why Lmod uses both ~/.lmod and ~/.config/lmod directories.   To remove a collection you can do: `module disable <collection>`

As for trying to use pin_version.  I cannot tell if it is working for you or not.  So let me be clear. 

Have you tried setting $LMOD_PIN_VERSIONS? If so does it work? 

Have you tried `module --pin_version restore`?  If so does it work?

There is no difference in the collection that is written out with or with-out $LMOD_PIN_VERSIONS being set.  The option --pin_version just sets $LMOD_PIN_VERSIONS internally.    Setting $LMOD_PIN_VERSIONS is only used when restoring a collection.  Internally, Lmod normally uses the "userName" which is the name that was used on the command line.  When $LMOD_PIN_VERSIONS is set, the fullName is used. Namely the name and version of a modulefile.

It has been a few years, but when I used a Cray, it was impossible to use collections.  The issue was then that the standard module environments were different  on the login nodes and the compute nodes.  That is `module load cray-cce` would have different modules loaded on the login and compute nodes.  The only way that a collection can be used is when the exact named modules are loaded especially when $LMOD_PIN_VERSIONS is set.   There can't be 20 modules loaded on the login node and 24 modules loaded on the compute node. 

Hope this helps.

**Comment by rtmclay** [comment]
Why Lmod writes to both ~/.lmod and ~/.config/lmod is discuss here: https://lmod.readthedocs.io/en/latest/025_new.html

**Comment by pawsey-kbuckley** [comment]
Ta for the pointer to the docs re the currently duplicated, but deprecated, writes.
Sounds as though we should be setting that 'transition' EnvVar for folk here.

Yes I treid using the LMOD_PIN_VERSIONS EnvVar: but no it didn't solve
the problem.

FWIW, it's not a number of modules mismatch: it's an ordering thing.

Typically one switches between various "Programing Environments"
by swapping say, a `PrgEnv-gnu`(our default)  to say `PrgEnv-cray`.

Doing so will also swap some other modules for you including the
compiler, so `gcc`(Gnu Compiler Collection) gets swapped out for
`cce` (Cray Compiler Collection).

Tha all works fie, however, one user has also seen that they can
also swao the `gcc` module for the `cce` one, and it appears to
do the right thing ...

... until, that is, they save that module environment.

It's the same number of modules, just a slightly different order, but
it refuses to restore.

Between you and I, the idea that we have to set up THREE seperate
"Programing Environments", even if the user logging in has no need
of ONE, let alone more than one, of them, for certain activities is, shall
we say "slightly suboptimal", compared to explictly loading what you
need, when you need it, but, even allowing for that nonsense, I have
never been able to see why the restore shouldn't work in this case.

Then I came across the idea of "pinning versions" and thought that
might offer a solution: as I say though Deep Sorrow!

We have a work around, even though it is "don't it that way if you want
to save an restore a working module environment: do it someother way",
so, as ever, thanks for your time and insight into things here: happy to
close as "Info Given"

Kevin Buckley
