### ISSUE TITLE
prereq() not picking up loaded module

### ISSUE THREAD

**Issue by abazabaaa** [TACC/Lmod#719]
**Describe the bug**
Using prereq('XX') does not work as intended. If you load module_a, and have module_b contain prereq('module_a') you will get an error that module_a is not loaded, despite module list showing it is loaded.

https://lmod.readthedocs.io/en/latest/015_writing_modules.html (prereq() example listed here)
 
**To Reproduce**

`mkdir test`
`cd test && touch module_a.lua`
`nano module_b.lua`
include the line prereq('module_a')
`module purge`
`module load test/module_a`
`module list`
Currently Loaded Modules:
  1) test/module_a

`module load test/module_b`
Lmod has detected the following error:  Cannot load module "test/module_b" without these module(s) loaded:
   test/module_a

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    test/module_b    /ap/modules/modulefiles/test/module_b.lua

**Expected behavior**
Expected behavior is that test/module_b will load since test/module_a is loaded.

**Desktop (please complete the following information):**
 - OS: Linux
 - Linux distribution: RHEL8
 - Lmod Version: Version 8.7.37
 - For Lmod Versions 8.7.7+, please run "module --miniConfig" and
   include the output here.

**Additional context**

**Comment by rtmclay** [comment]
This is not a bug.  According to the way that Lmod works.  You have a "shortname" or "sn" of test and two module versions. One is named "module_a" and the other is "module_b".  Because of the one name rule. module load test/module_b forces test/module_a to be unloaded.  

**For this module layout, you can only have ONE module named test loaded at a time**

Please read: https://lmod.readthedocs.io/en/latest/055_module_names.html

A different module layout will work.  For example:
```
% tree -a                                
.
├── module_a
│   └── 1.0.lua
└── module_b
    └── 1.0.lua
```
Now doing:
```
% module load module_a
% module load module_b
```
will work.

**Comment by abazabaaa** [comment]
I see, thanks for the explanation.
