### ISSUE TITLE
Error in LocationT:search()

### ISSUE THREAD

**Issue by rtmclay** [TACC/Lmod#734]
Bug report for issue reported on Lmod mailing list that reported that the following statement:

When a modulefile has the following statement in the lua file:

   prepend_path{"PATH", root, priority=100}

   Lmod has detected the following error:  Error in LocationT:search().

Attached is a tar file that should be used to provide a reproducer of the issue:

[user.tar.gz](https://github.com/user-attachments/files/17805494/user.tar.gz)

**Comment by eylenth** [comment]
It's working fine for me, since you are providing a cache directory with a spiderT.lua file that was updated with lmod from the the IS690-hide branch 

when loading modules without the version syntax and it is using lmod from IS690-hide branch, and the  spiderT.lua file cache was still updated from the 8.7.53 from the main branch. Then it was causing the `LocationT:search()` error
Which is normal behavior I guess. Lmod cache should be aligned with the module version/branch you are using ?

**Comment by rtmclay** [comment]
I am closing this issue.  If you find this happening again please reopen this issue.
