### ISSUE TITLE
Support non-bash shells

### ISSUE THREAD

**Issue by opoplawski** [TACC/Lmod#79]
init/profile will load lmod_bash_completions even if the shell is not bash, resulting in:
~~~~~
/usr/share/lmod/lmod/init/lmod_bash_completions: line 22: syntax error near unexpected token `('
/usr/share/lmod/lmod/init/lmod_bash_completions: line 22: `     comm -23  <(_module_avail|sort)  <(_module_loaded_modules|sort)'
~~~~~
I would suggest the following conditional from Fedora's environment-modules module.sh:
~~~~~
  shell=`/bin/basename \`/bin/ps -p $$ -ocomm=\``
  if [ -f @PKG@/init/$shell ]; then
    . @PKG@/init/$shell >/dev/null # Module Support
  else
     . @PKG@/init/sh >/dev/null # Module Support
  fi
~~~~~

**Comment by rtmclay** [comment]
But there is only bash and csh files in init so that particular trick won't work there.  The sh and zsh file are just copies of the bash file. However shell= trick is very cool.  I have modified init/bash.in to use the trick.  What surprises me is that the shell= trick works under MAC OS X as well.  The only problem is that basename and ps aren't guaranteed to be in /bin.  But a little configuration magic solves that problem.  

Thanks,

**Comment by opoplawski** [comment]
We're both a little confused.  It's not init/profile that's directly loading the bash_completion script, it's via init/bash.  And it's true that in /etc/profile.d there is only .sh/.csh, but init/sh.in and init/zsh.in are very different that init/bash.in and seems to work if the right one is chosen.  We just need to make sure to source the proper version from the profile script.

**Comment by rtmclay** [comment]
You are right and I'm wrong.  init/bash.in and init/zsh.in are the same init/bash.in and init/sh.in are different.  I have made the change to init/profile.in to match what you proposed in the beginning.

Thanks.

**Comment by rtmclay** [comment]
This change has been push to the git repo and is marked 6.0.12
