### ISSUE TITLE
Restore previous state on failed restore

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#80]
When a restore fails (changed module path or so), it would be nice if it could return to the state is was when the restore was issued. Currently, you're left with no modules loaded.

**Comment by rtmclay** [comment]
I have pushed 6.0.14 to github.  It does the following:
a) if the collection is not "default" then if the collection is bad then there is no change in the modules loaded

b) If the collection is "default" and the collection is bad, then Lmod tries to do a module reset.  If there is no modules defined in LMOD_SYSTEM_DEFAULT_MODULES then there is no change in the modules loaded

The reason for rule b is that if the "default" collection is bad, the user should get the system default.  Otherwise they will have no modules loaded at startup.

**Comment by wpoely86** [comment]
Tested, works great. Thanks!
