### ISSUE TITLE
bash tab completion for module use dir<TAB> doesn't work if _filedir isn't on system

### ISSUE THREAD

**Issue by rtmclay** [TACC/Lmod#86]
If the bash completion function _filedir is not there then you can't do tab completion for module use under bash.

**Comment by rtmclay** [comment]
Lmod version 6.5.5 fixes this problem.  At least in my tests.

**Comment by boegel** [comment]
@rtmclay I can confirm this is fixed in Lmod 6.5.5, where tab completion for paths works (e.g. `module use /tm<tab>` completes to `module use /tmp/`

What doesn't work is tab completion for environment variables though, which does work in other contexts... For example when `$PREFIX` is defined, `module use $PRE<tab>` doesn't complete to `module use $PREFIX` (it doesn't throw a nasty error either though, so that's definitely a step up).

I have no idea if this could be fixed as well, or how hard it would be. Maybe @pneerincx has an idea?

**Comment by pneerincx** [comment]
@boegel `module use $PRE<tab>` will autocomplete with #159 to module use $PREFIX, but only if that environment variable contains a valid/existing path to a directory. While I was at it I also added support for expanding `~` to home dirs.

**Comment by boegel** [comment]
@rtmclay this can be closed now? Thanks again @pneerincx!
